/*TRIGGERS - BACKUP AUTOMATICO EM OUTRA TABELA*/

/*DIGAMOS QUE SEJA NECESSÁRIO CRIAR UM BACKUP PARA GUARDAR
TODOS OS REGISTROS QUE SÃO DELETADOS DE UMA TABELA*/

USE COMERCIO;

SELECT * FROM CLIENTE;
/*
+-----------+---------+------+-------------------+--------------+
| IDCLIENTE | NOME    | SEXO | EMAIL             | CPF          |
+-----------+---------+------+-------------------+--------------+
|         1 | JOSE    | M    | JOSE@GMAIL.COM    | 12121212     |
|         2 | MARIA   | F    | MARIA@GMAIL.COM   | 1313131313   |
|         3 | CALEBE  | M    | CALEBE@GMAIL.COM  | 1414141414   |
|         4 | RUTE    | F    | RUTE@GMAIL.COM    | 151515151515 |
|         5 | RODRIGO | M    | RODRIGO@GMAIL.COM | 161616161616 |
|        11 | VICTOR  | M    | VICTOR@GMAIL.COM  | 16161616     |
+-----------+---------+------+-------------------+--------------+*/

CREATE TABLE BKUP_CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM("M","F") NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
					);

/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~ CRIANDO TRIGGER ~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
DELIMITER $
CREATE TRIGGER BACKUP_CLIENTE
BEFORE DELETE ON CLIENTE FOR EACH ROW
BEGIN
		INSERT INTO BKUP_CLIENTE VALUES (NULL,OLD.NOME,OLD.SEXO,OLD.EMAIL, OLD.CPF);
END
$
DELIMITER ;

/*VAMOS DELETAR ALUM REGISTRO E VERIFICAR SE ELE FOI PARA TABELA BKUP_CLIENTE

VAMOS DELETAT O REGISTRO COM ID = 11*/

DELETE FROM CLIENTE WHERE IDCLIENTE = 11;

SELECT * FROM BKUP_CLIENTE;
/*
+-----------+--------+------+------------------+----------+
| IDCLIENTE | NOME   | SEXO | EMAIL            | CPF      |
+-----------+--------+------+------------------+----------+
|         1 | VICTOR | M    | VICTOR@GMAIL.COM | 16161616 |
+-----------+--------+------+------------------+----------+*/

/*DIGAMOS QUE QUEREMOS CRIAR UM BACKUP EM OUTRA DATABASE AO INVÉS DE EM OUTRA TABELA*/

CREATE DATABASE BKP;
USE BKP;

CREATE TABLE BKUP_CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM("M","F") NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
					);

USE COMERCIO;

/*TODA VEZ QUE É FEITA UM INSERT NA TABELA CLIENTE DO BANCO COMERCIO VAMOS ADICIONAR TAMBÉM
NA TABELA BKUP_CLIENTE DO BANCO BKP*/

DELIMITER $
CREATE TRIGGER BKP_CLIENTE AFTER INSERT ON COMERCIO.CLIENTE FOR EACH ROW
BEGIN
		INSERT INTO BKP.BKUP_CLIENTE VALUES(NULL,NEW.NOME,NEW.SEXO,NEW.EMAIL,NEW.CPF);
END
$

DELIMITER ;

INSERT INTO COMERCIO.CLIENTE VALUES(NULL,"MACACO","M","MACACO@GMAIL.COM","17171717");

SELECT * FROM BKP.BKUP_CLIENTE;
/*
+-----------+--------+------+------------------+----------+
| IDCLIENTE | NOME   | SEXO | EMAIL            | CPF      |
+-----------+--------+------+------------------+----------+
|         1 | MACACO | M    | MACACO@GMAIL.COM | 17171717 |
+-----------+--------+------+------------------+----------+
* O REGISTRO SERÁ ADICIONADO TANTO NA TABELA COMERCIO.CLIENTE QUANTO NA TABELA BKP.BKUP_CLIENTE*/

/*
~~~~~~ ~~~~ ~~~~~~~~~~~~ ~~~~ ~~~~~~ TRIGGER UPDATE ~~~~~~ ~~~~ ~~~~~~ ~~~~~~ ~~~~ ~~~~~~

DIGAMOS QUE SEJA NECESSÁRIO FAZER UMA TABELA COM O BACKUP MAS COM ALGUMAS INFORMAÇÕES ADICIONAIS,
TODA VEZ QUE ALGUEM FAZER UMA MODIFICACAO NO NOME DE UM REGISTRO A TABELA BACKUP DEVE MOSTRAR O 
ANTIGO NOME E O NOVO NOME
*/

DROP TABLE BKP.BKUP_CLIENTE;

USE BKP;

CREATE TABLE BKP_CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	OLD_NOME VARCHAR(30),
	SEXO ENUM("M","F") NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE,
	DIA DATETIME
					);

USER COMERCIO;

DELIMITER $
CREATE TRIGGER TRIGGER_UPDATE_BKP AFTER UPDATE ON COMERCIO.CLIENTE FOR EACH ROW
BEGIN
		INSERT INTO BKP.BKP_CLIENTE VALUES(NULL,NEW.NOME,OLD.NOME,NEW.SEXO,NEW.EMAIL,NEW.CPF,NOW());
END
$

DELIMITER ;

UPDATE CLIENTE SET NOME = "MACACOJR" WHERE NOME = "MACACO";

SELECT * FROM BKP.BKP_CLIENTE;
/*
+-----------+----------+----------+------+------------------+----------+---------------------+
| IDCLIENTE | NOME     | OLD_NOME | SEXO | EMAIL            | CPF      | DIA                 |
+-----------+----------+----------+------+------------------+----------+---------------------+
|         1 | MACACOJR | MACACO   | M    | MACACO@GMAIL.COM | 17171717 | 2022-01-20 23:33:23 |
+-----------+----------+----------+------+------------------+----------+---------------------+*/

